name: Docker Start Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-start:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Docker Compose
      run: sudo apt-get update && sudo apt-get install -y docker-compose

    - name: Make start.sh executable
      run: chmod +x ./start.sh

    - name: Run start script
      run: ./start.sh

    - name: Wait and check containers
      run: |
        sleep 10
        docker ps
        docker-compose ps
